include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  errors:
    undefined_prefixed_name: ignore
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
